### ISSUE TITLE
PHP 8.1 displays warnings for php-code-search v 1.10.5

### ISSUE THREAD

**Issue by Hypnopompia** [permafrost-dev/php-code-search#31]
Trying to use spatie x-ray which requires php-code-search 1.10.5 and I see these warnings being generated when using PHP 8.1.

Deprecated: Return type of Permafrost\PhpCodeSearch\Support\Collections\Collection::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/thunter/Dropbox/Mac/src/hitlabs/pronto-api/src/vendor/permafrost-dev/php-code-search/src/Support/Collections/Enumerable.php on line 9

Deprecated: Return type of Permafrost\PhpCodeSearch\Support\Collections\Collection::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/thunter/Dropbox/Mac/src/hitlabs/pronto-api/src/vendor/permafrost-dev/php-code-search/src/Support/Collections/Enumerable.php on line 14

Deprecated: Return type of Permafrost\PhpCodeSearch\Support\Collections\Collection::offsetSet($key, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/thunter/Dropbox/Mac/src/hitlabs/pronto-api/src/vendor/permafrost-dev/php-code-search/src/Support/Collections/Enumerable.php on line 19

Deprecated: Return type of Permafrost\PhpCodeSearch\Support\Collections\Collection::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/thunter/Dropbox/Mac/src/hitlabs/pronto-api/src/vendor/permafrost-dev/php-code-search/src/Support/Collections/Enumerable.php on line 28

Deprecated: Return type of Permafrost\PhpCodeSearch\Support\Collections\Collection::current() should either be compatible with Iterator::current(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/thunter/Dropbox/Mac/src/hitlabs/pronto-api/src/vendor/permafrost-dev/php-code-search/src/Support/Collections/Enumerable.php on line 38

Deprecated: Return type of Permafrost\PhpCodeSearch\Support\Collections\Collection::next() should either be compatible with Iterator::next(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/thunter/Dropbox/Mac/src/hitlabs/pronto-api/src/vendor/permafrost-dev/php-code-search/src/Support/Collections/Enumerable.php on line 48

Deprecated: Return type of Permafrost\PhpCodeSearch\Support\Collections\Collection::key() should either be compatible with Iterator::key(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/thunter/Dropbox/Mac/src/hitlabs/pronto-api/src/vendor/permafrost-dev/php-code-search/src/Support/Collections/Enumerable.php on line 43

Deprecated: Return type of Permafrost\PhpCodeSearch\Support\Collections\Collection::valid() should either be compatible with Iterator::valid(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/thunter/Dropbox/Mac/src/hitlabs/pronto-api/src/vendor/permafrost-dev/php-code-search/src/Support/Collections/Enumerable.php on line 53

Deprecated: Return type of Permafrost\PhpCodeSearch\Support\Collections\Collection::rewind() should either be compatible with Iterator::rewind(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/thunter/Dropbox/Mac/src/hitlabs/pronto-api/src/vendor/permafrost-dev/php-code-search/src/Support/Collections/Enumerable.php on line 33

**Comment by patinthehat** [comment]
Thank you for the bug report, I will look into this.

**Comment by patinthehat** [comment]
@Hypnopompia I've published `v1.10.6`, which should fix the deprecation warnings you're seeings.  Are you able to confirm that the issue is resolved?

**Comment by Hypnopompia** [comment]
@patinthehat I can confirm that v.1.10.6 removes the warnings. Thanks!

However, when using the spatie/x-ray package in my laravel project, I am seeing this error:

`Call to undefined method Permafrost\PhpCodeSearch\Support\Collections\Collection::merge()`

It appears the collect() helper in https://github.com/permafrost-dev/php-code-search/blob/main/src/Support/helpers.php#L95-L100 is taking priority over the laravel collect() helper and returning a different Collection class, so when laravel tries to run the merge() method, it fails.

To resolve this, I just removed the x-ray package from my laravel project and installed the x-ray package globally using composer. Now it runs fine with no errors or warnings. I think x-ray was meant to be included in any project that also includes the ray package, so I'm not sure if there's a better way to handle the conflicting helper functions, but I'll leave that for you to decide. I have a workaround that is working for me.

Thanks so much!

**Comment by patinthehat** [comment]
@Hypnopompia I also wrote the `spatie\x-ray` package - I'll look into this issue now and patch it ASAP.  Thanks for the updated report!

A few follow up questions:

- Are you using `spatie\laravel-ray`?
- Can you provide more information from the error you're getting so I can locate the issue?

**Comment by Hypnopompia** [comment]
Yes, my composer.json includes:
`"spatie/laravel-ray": "^1.28"`

The error is thrown when running the ./artisan command:

```
./artisan

In app.php line 237:
Call to undefined method Permafrost\PhpCodeSearch\Support\Collections\Collection::merge()
```

in my config/app.php file, line 237 is

`'aliases' => Facade::defaultAliases()->merge([`

![CleanShot 2023-11-10 at 14 31 51](https://github.com/permafrost-dev/php-code-search/assets/673731/8121c9d6-42b6-4a0c-b573-9dee27238f4c)

In `Facade::defaultAliases()`, it looks like this:

![CleanShot 2023-11-10 at 14 35 01](https://github.com/permafrost-dev/php-code-search/assets/673731/a2e49727-7233-4ca2-be2f-1eb79948fe88)


Hopefully that helps. Let me know if there is any other information I can provide.

**Comment by patinthehat** [comment]
@Hypnopompia I've published [v1.11.0](https://github.com/permafrost-dev/php-code-search/releases/tag/1.11.0), could you see if this resolves the issue you reported when `x-ray` is installed locally _(project-level)_ instead of globally?

**Comment by Hypnopompia** [comment]
@patinthehat yep, I can confirm that the error I was seeing is no longer there. Looks good! Thanks so much.

**Comment by patinthehat** [comment]
Great! Thanks again for the reports and prompt/helpful responses :+1:
